SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS phase3b_migrate;
DELIMITER $$
CREATE PROCEDURE phase3b_migrate()
BEGIN
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='flommast' AND COLUMN_NAME='mast_share_value') THEN
    ALTER TABLE flommast ADD COLUMN mast_share_value DECIMAL(13,2) NOT NULL DEFAULT 0.00;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='flommast' AND COLUMN_NAME='member_type_code') THEN
    ALTER TABLE flommast ADD COLUMN member_type_code VARCHAR(10) NOT NULL DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='flommast' AND INDEX_NAME='idx_member_type_code') THEN
    ALTER TABLE flommast ADD INDEX idx_member_type_code (member_type_code);
  END IF;
END$$
DELIMITER ;
CALL phase3b_migrate();
DROP PROCEDURE phase3b_migrate;

CREATE TABLE IF NOT EXISTS savings_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mast_memb_no VARCHAR(20) NOT NULL,
  full_name VARCHAR(255) NOT NULL DEFAULT '',
  account_no VARCHAR(20) NOT NULL,
  balance DECIMAL(15,4) NOT NULL DEFAULT 0,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_member_account (mast_memb_no, account_no),
  KEY idx_memb_no (mast_memb_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
