#!/usr/bin/env bash
# ============================================================
# ให้ nginx รู้ IP จริงของผู้ใช้เมื่อ request ผ่าน Cloudflare (proxy สีส้ม)
#
# ถ้าไม่ตั้ง: $remote_addr = IP ของ Cloudflare → X-Real-IP ที่ส่งให้ API ผิด
#   → rate limit นับรวมทุกคนที่ผ่าน edge เดียวกัน, audit log เห็นแต่ IP Cloudflare
#
# ปลอดภัยที่จะรันก่อนย้ายไป Cloudflare: nginx จะเชื่อ header CF-Connecting-IP
# เฉพาะ request ที่มาจาก IP ของ Cloudflare จริงเท่านั้น (คนอื่นปลอม header ไม่ได้)
#
# รันซ้ำได้ (อัปเดตรายการ IP) — ควรรันเดือนละครั้ง หรือตั้ง cron
# ใช้งาน (root บน VPS):  bash /var/www/loaneasy/scripts/ops/cloudflare-realip.sh
# ============================================================
set -euo pipefail

CONF=/etc/nginx/conf.d/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

v4="$(curl -fsS -m 20 https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS -m 20 https://www.cloudflare.com/ips-v6)"

# กันไฟล์เสีย: ต้องได้รายการ CIDR จริง
count="$(printf '%s\n%s\n' "$v4" "$v6" | grep -cE '^[0-9a-fA-F:.]+/[0-9]+$' || true)"
if [ "$count" -lt 10 ]; then
  echo "ERROR: got only $count Cloudflare ranges — not touching nginx" >&2
  exit 1
fi

{
  echo "# Generated by scripts/ops/cloudflare-realip.sh on $(date -Iseconds) — do not edit by hand"
  echo "# Trust CF-Connecting-IP only from Cloudflare edge IPs"
  printf '%s\n%s\n' "$v4" "$v6" | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' | sed 's/^/set_real_ip_from /; s/$/;/'
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

[ -f "$CONF" ] && cp -p "$CONF" "$CONF.bak"
install -m 644 "$TMP" "$CONF"

if nginx -t 2>/dev/null; then
  systemctl reload nginx
  echo "OK: $count Cloudflare ranges trusted, nginx reloaded ($CONF)"
else
  echo "ERROR: nginx -t failed — restoring previous config" >&2
  if [ -f "$CONF.bak" ]; then mv "$CONF.bak" "$CONF"; else rm -f "$CONF"; fi
  nginx -t
  exit 1
fi
